version: 2

sources:
  - name: hevo_raw
    # We use a variable here so it's not "hardcoded"
    database: "{{ var('raw_database', 'CUSTOMERS') }}" 
    schema: "{{ var('raw_schema', 'DEMO_PUBLIC') }}"
    tables:
      - name: raw_customers
      - name: raw_orders
      - name: raw_payments